### ISSUE TITLE
如何让2233板娘固定

### ISSUE THREAD

**Issue by Spirei** [xb2016/poster-girl-l2d-2233#1]
感觉浏览网站的同时 2233跳来跳去会遮挡要阅读的内容..需要去托拽 有没有什么办法能够使其固定或者只在文章两侧空白处出自由活动..

**Comment by xb2016** [comment]
以下方法仅供参考，具体需要自己细调。

### 将下列部分进行修改可取消自动漂移功能：

> window.setInterval(function(){
>         var temp = Math.random();
>         if(temp>0.35){
>             showMessage(showHitokoto());
>         }else{
>             msgs = ["乾坤大挪移！","我飘过来了！~","我飘过去了","我得意地飘！~飘！~"];
>             var i = Math.floor(Math.random()*msgs.length);
>             s = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.75,-0.1,-0.2,-0.3,-0.4,-0.5,-0.6,-0.7,-0.75];
>             var i1 = Math.floor(Math.random()*s.length);
>             var i2 = Math.floor(Math.random()*s.length);
>                 $(".waifu").animate({
>                     left:document.body.offsetWidth/2*(1+s[i1]),
>                     top:(window.innerHeight+$(window).scrollTop()-300)-(window.innerHeight-270)/2*(1+s[i2])
>                 },
>                 {
>                     duration:2000,
>                     complete:showMessage(msgs[i])
>                 });
>         }
>     },40000);

修改为：

> window.setInterval(function(){showMessage(showHitokoto());},30000);

### 限定浮动区域：

对上述代码中的left与top值进行限定即可。

### 完全固定：

1. 将`.waifu`的`position`值改为`fixed`，并调整位置；

2. 移除`waifu-tips.js`中所有关于`animate`的部分。

**Comment by Spirei** [comment]
非常感谢 已解决~@xb2016
