### ISSUE TITLE
关于ajax的问题

### ISSUE THREAD

**Issue by LittleStarsQAQ** [xb2016/poster-girl-l2d-2233#2]
您好，非常喜欢您写的2233看板娘，请问有办法让看板娘支持ajax或pjax加载吗？

期待您的回复~非常感谢！！！

**Comment by xb2016** [comment]
@NTDLX 请具体解释下“支持ajax或pjax加载”，最好贴个有问题的演示站

**Comment by Hcreak** [comment]
@NTDLX 话说你的站或者说你用的主题支持ajax 看板娘就不就不会重新加载了不是么
