### ISSUE TITLE
怎么她突然就隐形了 jq和font-awesome用的都是您提供的

### ISSUE THREAD

**Issue by ghost** [xb2016/poster-girl-l2d-2233#5]
![0516-214025](https://user-images.githubusercontent.com/42313791/57858296-5d89a100-7823-11e9-825f-fcd9ad70d0ee.png)
![0516-214051](https://user-images.githubusercontent.com/42313791/57858298-5d89a100-7823-11e9-9d05-fec86cd0288a.png)

**Comment by ghost** [comment]
我的网站 liruichen.com

**Comment by Hola-Net** [comment]
请确保mime类型中包含以下三件套：
.mtn的mime类型: application/octet-stream
.moc的mime类型：application/x-mocha
.json的mime类型：application/json
再检查一下Wordpress设置中的站点地址和Wordpress地址是否正确，并在插件设置中开启
 jQuery 库与 Font Awesome 4.7 配置


若配置不正确则会出现隐形的情况
