### ISSUE TITLE
作者您好，能否提供一下关于解决默认看板娘是22还是33还有手机端显示的思路呢（新版）

### ISSUE THREAD

**Issue by lxsjgzs** [xb2016/poster-girl-l2d-2233#8]
确实在研读了新版的与旧版的的代码能发现很多不同（原谅我仅仅是会看并且只能理解大体意思），昨天晚上搞了一个晚上只是找到了如何更改 hitogoto 还有 info 的 function （博客以后可能会面向学生，所以更改了很多会说的话，并且将 info 更改连接到你的 GitHub 地址下）。现在想请问作者如果可以的话能否提供一下 默认看板是 22 还是 33 还有手机端显示的思路么？

在此感谢！

**Comment by xb2016** [comment]
模型默认值：waifu-tips.js:44 `model_p=` 与 waifu-tips.js:62 `p=`，两者数据相反；
手机端显示的参考：移除 CSS: `@media(max-width:530px){.l2d_xb{display:none!important}}`，然后通过 js 实现，通过判断窗口大小，小于一定值，修改 .waifu 的大小为移动端合适值，同时可以隐藏一些移动端不方便操作的元素。
个人并不建议在移动端显示，没有必要，空占资源。

**Comment by lxsjgzs** [comment]
感谢！
